services:
    webmoviesapigw:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "5200:8080"
            - "5201:8081"
        volumes:
            - ./src/ApiGateways/Web.Bff.Movies:/app/configuration